# Railway Backend Configuration
[build]
builder = "nixpacks"

[deploy]
startCommand = "cd Backend/todo && poetry run uvicorn src.todo.main:app --host 0.0.0.0 --port $PORT"

[env]
PYTHONPATH = "/app/Backend/todo/src"
